// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: ingestworker.proto

package ingestworker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XId           string                 `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	Categories    *Category              `protobuf:"bytes,2,opt,name=categories,proto3" json:"categories,omitempty"`
	Title         *Title                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Posted        float64                `protobuf:"fixed64,5,opt,name=posted,proto3" json:"posted,omitempty"` // Unix time in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ad) Reset() {
	*x = Ad{}
	mi := &file_ingestworker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ad) ProtoMessage() {}

func (x *Ad) ProtoReflect() protoreflect.Message {
	mi := &file_ingestworker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ad.ProtoReflect.Descriptor instead.
func (*Ad) Descriptor() ([]byte, []int) {
	return file_ingestworker_proto_rawDescGZIP(), []int{0}
}

func (x *Ad) GetXId() string {
	if x != nil {
		return x.XId
	}
	return ""
}

func (x *Ad) GetCategories() *Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Ad) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Ad) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Ad) GetPosted() float64 {
	if x != nil {
		return x.Posted
	}
	return 0
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subcategory   string                 `protobuf:"bytes,1,opt,name=subcategory,proto3" json:"subcategory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_ingestworker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_ingestworker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_ingestworker_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetSubcategory() string {
	if x != nil {
		return x.Subcategory
	}
	return ""
}

type Title struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ro            string                 `protobuf:"bytes,1,opt,name=ro,proto3" json:"ro,omitempty"`
	Ru            string                 `protobuf:"bytes,2,opt,name=ru,proto3" json:"ru,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_ingestworker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_ingestworker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_ingestworker_proto_rawDescGZIP(), []int{2}
}

func (x *Title) GetRo() string {
	if x != nil {
		return x.Ro
	}
	return ""
}

func (x *Title) GetRu() string {
	if x != nil {
		return x.Ru
	}
	return ""
}

// Define the GetDataResponse message
type GetDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ads           []*Ad                  `protobuf:"bytes,1,rep,name=ads,proto3" json:"ads,omitempty"` // List of ads
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataResponse) Reset() {
	*x = GetDataResponse{}
	mi := &file_ingestworker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataResponse) ProtoMessage() {}

func (x *GetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ingestworker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataResponse.ProtoReflect.Descriptor instead.
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return file_ingestworker_proto_rawDescGZIP(), []int{3}
}

func (x *GetDataResponse) GetAds() []*Ad {
	if x != nil {
		return x.Ads
	}
	return nil
}

// Define an empty message for the request
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_ingestworker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_ingestworker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_ingestworker_proto_rawDescGZIP(), []int{4}
}

var File_ingestworker_proto protoreflect.FileDescriptor

const file_ingestworker_proto_rawDesc = "" +
	"\n" +
	"\x12ingestworker.proto\"\x8a\x01\n" +
	"\x02Ad\x12\x0f\n" +
	"\x03_id\x18\x01 \x01(\tR\x02Id\x12)\n" +
	"\n" +
	"categories\x18\x02 \x01(\v2\t.CategoryR\n" +
	"categories\x12\x1c\n" +
	"\x05title\x18\x03 \x01(\v2\x06.TitleR\x05title\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06posted\x18\x05 \x01(\x01R\x06posted\",\n" +
	"\bCategory\x12 \n" +
	"\vsubcategory\x18\x01 \x01(\tR\vsubcategory\"'\n" +
	"\x05Title\x12\x0e\n" +
	"\x02ro\x18\x01 \x01(\tR\x02ro\x12\x0e\n" +
	"\x02ru\x18\x02 \x01(\tR\x02ru\"(\n" +
	"\x0fGetDataResponse\x12\x15\n" +
	"\x03ads\x18\x01 \x03(\v2\x03.AdR\x03ads\"\a\n" +
	"\x05Empty23\n" +
	"\fRetrieveData\x12#\n" +
	"\aGetData\x12\x06.Empty\x1a\x10.GetDataResponseB9Z7github.com/skybytescode/elastic-grpc/proto/ingestworkerb\x06proto3"

var (
	file_ingestworker_proto_rawDescOnce sync.Once
	file_ingestworker_proto_rawDescData []byte
)

func file_ingestworker_proto_rawDescGZIP() []byte {
	file_ingestworker_proto_rawDescOnce.Do(func() {
		file_ingestworker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestworker_proto_rawDesc), len(file_ingestworker_proto_rawDesc)))
	})
	return file_ingestworker_proto_rawDescData
}

var file_ingestworker_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ingestworker_proto_goTypes = []any{
	(*Ad)(nil),              // 0: Ad
	(*Category)(nil),        // 1: Category
	(*Title)(nil),           // 2: Title
	(*GetDataResponse)(nil), // 3: GetDataResponse
	(*Empty)(nil),           // 4: Empty
}
var file_ingestworker_proto_depIdxs = []int32{
	1, // 0: Ad.categories:type_name -> Category
	2, // 1: Ad.title:type_name -> Title
	0, // 2: GetDataResponse.ads:type_name -> Ad
	4, // 3: RetrieveData.GetData:input_type -> Empty
	3, // 4: RetrieveData.GetData:output_type -> GetDataResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ingestworker_proto_init() }
func file_ingestworker_proto_init() {
	if File_ingestworker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestworker_proto_rawDesc), len(file_ingestworker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestworker_proto_goTypes,
		DependencyIndexes: file_ingestworker_proto_depIdxs,
		MessageInfos:      file_ingestworker_proto_msgTypes,
	}.Build()
	File_ingestworker_proto = out.File
	file_ingestworker_proto_goTypes = nil
	file_ingestworker_proto_depIdxs = nil
}
