// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: ingestworker.proto

package ingestworker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RetrieveData_GetData_FullMethodName = "/RetrieveData/GetData"
)

// RetrieveDataClient is the client API for RetrieveData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RetrieveData returns the ads the worker has ingested.
type RetrieveDataClient interface {
	GetData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetDataResponse, error)
}

type retrieveDataClient struct {
	cc grpc.ClientConnInterface
}

func NewRetrieveDataClient(cc grpc.ClientConnInterface) RetrieveDataClient {
	return &retrieveDataClient{cc}
}

func (c *retrieveDataClient) GetData(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataResponse)
	err := c.cc.Invoke(ctx, RetrieveData_GetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RetrieveDataServer is the server API for RetrieveData service.
// All implementations must embed UnimplementedRetrieveDataServer
// for forward compatibility.
//
// RetrieveData returns the ads the worker has ingested.
type RetrieveDataServer interface {
	GetData(context.Context, *Empty) (*GetDataResponse, error)
	mustEmbedUnimplementedRetrieveDataServer()
}

// UnimplementedRetrieveDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRetrieveDataServer struct{}

func (UnimplementedRetrieveDataServer) GetData(context.Context, *Empty) (*GetDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetData not implemented")
}
func (UnimplementedRetrieveDataServer) mustEmbedUnimplementedRetrieveDataServer() {}
func (UnimplementedRetrieveDataServer) testEmbeddedByValue()                      {}

// UnsafeRetrieveDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RetrieveDataServer will
// result in compilation errors.
type UnsafeRetrieveDataServer interface {
	mustEmbedUnimplementedRetrieveDataServer()
}

func RegisterRetrieveDataServer(s grpc.ServiceRegistrar, srv RetrieveDataServer) {
	// If the following call panics, it indicates UnimplementedRetrieveDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RetrieveData_ServiceDesc, srv)
}

func _RetrieveData_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieveDataServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrieveData_GetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieveDataServer).GetData(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RetrieveData_ServiceDesc is the grpc.ServiceDesc for RetrieveData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RetrieveData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RetrieveData",
	HandlerType: (*RetrieveDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _RetrieveData_GetData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ingestworker.proto",
}
